name: Linting and testing

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --deploy --dev
    - run: pipenv run isort --recursive --diff
    - run: pipenv run black --check .
    - run: pipenv run flake8
    - run: pipenv run pytest
